import json
import urllib.request
import urllib.error
from typing import Dict, Any

OLLAMA_URL = "http://127.0.0.1:11434/api/generate"
MODEL_NAME = "llama3.2:3b"

def generate_rri_report(agniveer_name: str, rri_data: Dict[str, Any]) -> str:
    """
    Generates a performance summary and retention report using Ollama.
    """
    
    # Construct Prompt
    prompt = f"""
    Role: You are a Commanding Officer analyzing the Retention Readiness of an Agniveer soldier.
    Task: Write a concise 3-4 sentence summary report based on the following data. Focus on strengths, weaknesses, and a final recommendation for retention.

    Soldier: {agniveer_name}
    RRI Score: {rri_data.get('rri_score')} / 100 (Band: {rri_data.get('retention_band')})
    
    Technical Skills ({rri_data.get('technical_component')}/50):
    - Breakdown: {rri_data.get('technical_breakdown')}
    
    Behavioral Competencies ({rri_data.get('behavioral_component')}/30):
    - Status: {rri_data.get('behavioral_status')}
    - Trend: {rri_data.get('behavioral_trend')}
    
    Achievements ({rri_data.get('achievement_component')}/20):
    - Count: {rri_data.get('achievement_count')}
    
    Report:
    """

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.7,
            "num_predict": 200
        }
    }

    try:
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            OLLAMA_URL, 
            data=data, 
            headers={"Content-Type": "application/json"}
        )
        
        with urllib.request.urlopen(req) as response:
            if response.status == 200:
                result = json.loads(response.read().decode("utf-8"))
                return result.get("response", "No response generated by AI.")
            else:
                return f"Error: Ollama returned status {response.status}"
                
    except urllib.error.URLError as e:
        return f"Connection Failed: Ensure Ollama is running at {OLLAMA_URL}. details: {str(e)}"
    except Exception as e:
        return f"AI Generation Failed: {str(e)}"
