"""Initial schema

Revision ID: d075d28e9ef9
Revises: 
Create Date: 2026-01-13 09:48:34.669819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd075d28e9ef9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agniveers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('batch_no', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('reporting_date', sa.DateTime(), nullable=True),
    sa.Column('nok_name', sa.String(), nullable=True),
    sa.Column('nok_phone', sa.String(), nullable=True),
    sa.Column('hometown_address', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_branch', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('pan_card', sa.String(), nullable=True),
    sa.Column('adhaar_card', sa.String(), nullable=True),
    sa.Column('higher_qualification', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('joining_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agniveers_id'), 'agniveers', ['id'], unique=False)
    op.create_index(op.f('ix_agniveers_service_id'), 'agniveers', ['service_id'], unique=True)
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agniveer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SPORTS', 'TECHNICAL', 'LEADERSHIP', 'BRAVERY', 'INNOVATION', 'TRAINING', 'DISCIPLINARY', name='achievementtype'), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('date_earned', sa.DateTime(), nullable=False),
    sa.Column('validity_months', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agniveer_id'], ['agniveers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('behavioral_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agniveer_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.Column('quarter', sa.String(), nullable=True),
    sa.Column('initiative', sa.Float(), nullable=True),
    sa.Column('dedication', sa.Float(), nullable=True),
    sa.Column('team_spirit', sa.Float(), nullable=True),
    sa.Column('courage', sa.Float(), nullable=True),
    sa.Column('motivation', sa.Float(), nullable=True),
    sa.Column('adaptability', sa.Float(), nullable=True),
    sa.Column('communication', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agniveer_id'], ['agniveers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_assessments_id'), 'behavioral_assessments', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agniveer_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(), nullable=False),
    sa.Column('recipient_role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agniveer_id'], ['agniveers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('retention_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agniveer_id', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=True),
    sa.Column('rri_score', sa.Float(), nullable=False),
    sa.Column('retention_band', sa.Enum('GREEN', 'AMBER', 'RED', name='rriband'), nullable=False),
    sa.Column('technical_component', sa.Float(), nullable=True),
    sa.Column('behavioral_component', sa.Float(), nullable=True),
    sa.Column('achievement_component', sa.Float(), nullable=True),
    sa.Column('technical_completeness', sa.Float(), nullable=True),
    sa.Column('behavioral_completeness', sa.Float(), nullable=True),
    sa.Column('overall_data_quality', sa.Float(), nullable=True),
    sa.Column('audit_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agniveer_id'], ['agniveers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_readiness_id'), 'retention_readiness', ['id'], unique=False)
    op.create_table('technical_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agniveer_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.Column('firing_score', sa.Float(), nullable=True),
    sa.Column('weapon_handling_score', sa.Float(), nullable=True),
    sa.Column('tactical_score', sa.Float(), nullable=True),
    sa.Column('cognitive_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agniveer_id'], ['agniveers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_assessments_id'), 'technical_assessments', ['id'], unique=False)
    op.create_table('users_auth',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('AGNIVEER', 'COY_CDR', 'COY_CLK', 'CO', 'OFFICER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('agniveer_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('assigned_company', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agniveer_id'], ['agniveers.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_auth_user_id'), 'users_auth', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_auth_username'), 'users_auth', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_auth.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('recipient_ids_json', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_auth.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_id'), 'email_drafts', ['id'], unique=False)
    op.create_table('internal_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('is_deleted_by_sender', sa.Boolean(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users_auth.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_emails_id'), 'internal_emails', ['id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users_auth.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_table('rate_limit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_auth.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_logs_id'), 'rate_limit_logs', ['id'], unique=False)
    op.create_table('email_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('folder', sa.String(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['internal_emails.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users_auth.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_recipients_id'), 'email_recipients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_recipients_id'), table_name='email_recipients')
    op.drop_table('email_recipients')
    op.drop_index(op.f('ix_rate_limit_logs_id'), table_name='rate_limit_logs')
    op.drop_table('rate_limit_logs')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_internal_emails_id'), table_name='internal_emails')
    op.drop_table('internal_emails')
    op.drop_index(op.f('ix_email_drafts_id'), table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_auth_username'), table_name='users_auth')
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users_auth')
    op.drop_table('users_auth')
    op.drop_index(op.f('ix_technical_assessments_id'), table_name='technical_assessments')
    op.drop_table('technical_assessments')
    op.drop_index(op.f('ix_retention_readiness_id'), table_name='retention_readiness')
    op.drop_table('retention_readiness')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_behavioral_assessments_id'), table_name='behavioral_assessments')
    op.drop_table('behavioral_assessments')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_agniveers_service_id'), table_name='agniveers')
    op.drop_index(op.f('ix_agniveers_id'), table_name='agniveers')
    op.drop_table('agniveers')
    # ### end Alembic commands ###
